/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DriverOnboardingRouteImport } from './routes/driver-onboarding'
import { Route as ChooseModeRouteImport } from './routes/choose-mode'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppRequestsIndexRouteImport } from './routes/_app/requests/index'
import { Route as AppQuotesIndexRouteImport } from './routes/_app/quotes/index'
import { Route as AppJobsIndexRouteImport } from './routes/_app/jobs/index'
import { Route as AppAvailableIndexRouteImport } from './routes/_app/available/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppRequestsNewRouteImport } from './routes/_app/requests/new'
import { Route as AppRequestsIdRouteImport } from './routes/_app/requests/$id'
import { Route as AppJobsIdRouteImport } from './routes/_app/jobs/$id'
import { Route as AppDriversIdRouteImport } from './routes/_app/drivers/$id'
import { Route as AppAvailableIdRouteImport } from './routes/_app/available/$id'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminDriversRouteImport } from './routes/_app/admin/drivers'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverOnboardingRoute = DriverOnboardingRouteImport.update({
  id: '/driver-onboarding',
  path: '/driver-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseModeRoute = ChooseModeRouteImport.update({
  id: '/choose-mode',
  path: '/choose-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsIndexRoute = AppRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesIndexRoute = AppQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppRoute,
} as any)
const AppAvailableIndexRoute = AppAvailableIndexRouteImport.update({
  id: '/available/',
  path: '/available/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppRequestsNewRoute = AppRequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsIdRoute = AppRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIdRoute = AppJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDriversIdRoute = AppDriversIdRouteImport.update({
  id: '/drivers/$id',
  path: '/drivers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAvailableIdRoute = AppAvailableIdRouteImport.update({
  id: '/available/$id',
  path: '/available/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDriversRoute = AppAdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/choose-mode': typeof ChooseModeRoute
  '/driver-onboarding': typeof DriverOnboardingRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/admin/drivers': typeof AppAdminDriversRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/available/$id': typeof AppAvailableIdRoute
  '/drivers/$id': typeof AppDriversIdRoute
  '/jobs/$id': typeof AppJobsIdRoute
  '/requests/$id': typeof AppRequestsIdRoute
  '/requests/new': typeof AppRequestsNewRoute
  '/admin/': typeof AppAdminIndexRoute
  '/available/': typeof AppAvailableIndexRoute
  '/jobs/': typeof AppJobsIndexRoute
  '/quotes/': typeof AppQuotesIndexRoute
  '/requests/': typeof AppRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/choose-mode': typeof ChooseModeRoute
  '/driver-onboarding': typeof DriverOnboardingRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/profile': typeof AppProfileRoute
  '/admin/drivers': typeof AppAdminDriversRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/available/$id': typeof AppAvailableIdRoute
  '/drivers/$id': typeof AppDriversIdRoute
  '/jobs/$id': typeof AppJobsIdRoute
  '/requests/$id': typeof AppRequestsIdRoute
  '/requests/new': typeof AppRequestsNewRoute
  '/admin': typeof AppAdminIndexRoute
  '/available': typeof AppAvailableIndexRoute
  '/jobs': typeof AppJobsIndexRoute
  '/quotes': typeof AppQuotesIndexRoute
  '/requests': typeof AppRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/choose-mode': typeof ChooseModeRoute
  '/driver-onboarding': typeof DriverOnboardingRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/admin/drivers': typeof AppAdminDriversRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/available/$id': typeof AppAvailableIdRoute
  '/_app/drivers/$id': typeof AppDriversIdRoute
  '/_app/jobs/$id': typeof AppJobsIdRoute
  '/_app/requests/$id': typeof AppRequestsIdRoute
  '/_app/requests/new': typeof AppRequestsNewRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/available/': typeof AppAvailableIndexRoute
  '/_app/jobs/': typeof AppJobsIndexRoute
  '/_app/quotes/': typeof AppQuotesIndexRoute
  '/_app/requests/': typeof AppRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/choose-mode'
    | '/driver-onboarding'
    | '/login'
    | '/signup'
    | '/admin'
    | '/profile'
    | '/admin/drivers'
    | '/admin/users'
    | '/available/$id'
    | '/drivers/$id'
    | '/jobs/$id'
    | '/requests/$id'
    | '/requests/new'
    | '/admin/'
    | '/available/'
    | '/jobs/'
    | '/quotes/'
    | '/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/choose-mode'
    | '/driver-onboarding'
    | '/login'
    | '/signup'
    | '/profile'
    | '/admin/drivers'
    | '/admin/users'
    | '/available/$id'
    | '/drivers/$id'
    | '/jobs/$id'
    | '/requests/$id'
    | '/requests/new'
    | '/admin'
    | '/available'
    | '/jobs'
    | '/quotes'
    | '/requests'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/choose-mode'
    | '/driver-onboarding'
    | '/login'
    | '/signup'
    | '/_app/admin'
    | '/_app/profile'
    | '/_app/admin/drivers'
    | '/_app/admin/users'
    | '/_app/available/$id'
    | '/_app/drivers/$id'
    | '/_app/jobs/$id'
    | '/_app/requests/$id'
    | '/_app/requests/new'
    | '/_app/admin/'
    | '/_app/available/'
    | '/_app/jobs/'
    | '/_app/quotes/'
    | '/_app/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ChooseModeRoute: typeof ChooseModeRoute
  DriverOnboardingRoute: typeof DriverOnboardingRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-onboarding': {
      id: '/driver-onboarding'
      path: '/driver-onboarding'
      fullPath: '/driver-onboarding'
      preLoaderRoute: typeof DriverOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-mode': {
      id: '/choose-mode'
      path: '/choose-mode'
      fullPath: '/choose-mode'
      preLoaderRoute: typeof ChooseModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests/': {
      id: '/_app/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof AppRequestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/': {
      id: '/_app/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AppQuotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/': {
      id: '/_app/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/available/': {
      id: '/_app/available/'
      path: '/available'
      fullPath: '/available/'
      preLoaderRoute: typeof AppAvailableIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/requests/new': {
      id: '/_app/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof AppRequestsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests/$id': {
      id: '/_app/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof AppRequestsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/$id': {
      id: '/_app/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AppJobsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drivers/$id': {
      id: '/_app/drivers/$id'
      path: '/drivers/$id'
      fullPath: '/drivers/$id'
      preLoaderRoute: typeof AppDriversIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/available/$id': {
      id: '/_app/available/$id'
      path: '/available/$id'
      fullPath: '/available/$id'
      preLoaderRoute: typeof AppAvailableIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/drivers': {
      id: '/_app/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AppAdminDriversRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminDriversRoute: typeof AppAdminDriversRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminDriversRoute: AppAdminDriversRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppAvailableIdRoute: typeof AppAvailableIdRoute
  AppDriversIdRoute: typeof AppDriversIdRoute
  AppJobsIdRoute: typeof AppJobsIdRoute
  AppRequestsIdRoute: typeof AppRequestsIdRoute
  AppRequestsNewRoute: typeof AppRequestsNewRoute
  AppAvailableIndexRoute: typeof AppAvailableIndexRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
  AppQuotesIndexRoute: typeof AppQuotesIndexRoute
  AppRequestsIndexRoute: typeof AppRequestsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppAvailableIdRoute: AppAvailableIdRoute,
  AppDriversIdRoute: AppDriversIdRoute,
  AppJobsIdRoute: AppJobsIdRoute,
  AppRequestsIdRoute: AppRequestsIdRoute,
  AppRequestsNewRoute: AppRequestsNewRoute,
  AppAvailableIndexRoute: AppAvailableIndexRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
  AppQuotesIndexRoute: AppQuotesIndexRoute,
  AppRequestsIndexRoute: AppRequestsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ChooseModeRoute: ChooseModeRoute,
  DriverOnboardingRoute: DriverOnboardingRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
