name: Deploy Back

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy Back
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: apps/back
          command: deploy --minify
          packageManager: pnpm
